wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.13
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1649669295
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 19
      4: 3.8.10
      5: 0.12.13
      8:
      - 5
      10:
      - 4
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 12
learning_rate:
  desc: null
  value: 0.003
